{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.targets.wsl.bindMountRoot;
  
  # For non-NixOS systems, we need to:
  # 1. Configure wsl.conf with boot command
  # 2. Execute immediate mount command
  wslConfBootCommand = "mount --bind / ${cfg.mountpoint}/ -o x-mount.mkdir";
  
  # Script to configure /etc/wsl.conf
  configureWslConf = pkgs.writeShellScript "configure-wsl-conf" ''
    set -euo pipefail
    
    WSL_CONF="/etc/wsl.conf"
    TEMP_CONF=$(mktemp)
    
    echo "Configuring WSL bind mount in $WSL_CONF..."
    
    # Read existing wsl.conf or create basic structure
    if [[ -f "$WSL_CONF" ]]; then
      cp "$WSL_CONF" "$TEMP_CONF"
    else
      cat > "$TEMP_CONF" << 'EOF'
# WSL Configuration
# Generated by home-manager WSL targets module

[boot]
systemd = true

[automount]
enabled = true
EOF
    fi
    
    # Check if [boot] section exists and has our command
    if grep -q "^\[boot\]" "$TEMP_CONF"; then
      # [boot] section exists, check for our command
      if ! grep -q "command.*mount --bind / ${cfg.mountpoint}" "$TEMP_CONF"; then
        # Add or update the command
        if grep -q "^command" "$TEMP_CONF"; then
          # Replace existing command
          sed -i "/^\[boot\]/,/^\[/{s/^command.*/command = \"${wslConfBootCommand}\"/}" "$TEMP_CONF"
        else
          # Add command after [boot] line
          sed -i "/^\[boot\]/a command = \"${wslConfBootCommand}\"" "$TEMP_CONF"
        fi
      fi
    else
      # No [boot] section, add it
      cat >> "$TEMP_CONF" << EOF

[boot]
systemd = true
command = "${wslConfBootCommand}"
EOF
    fi
    
    # Apply the configuration atomically
    sudo cp "$TEMP_CONF" "$WSL_CONF"
    rm "$TEMP_CONF"
    
    echo "WSL configuration updated. Boot command: ${wslConfBootCommand}"
  '';
  
  # Script to execute immediate mount
  executeImmediateMount = pkgs.writeShellScript "execute-immediate-mount" ''
    set -euo pipefail
    
    echo "Setting up immediate bind mount: / -> ${cfg.mountpoint}"
    
    # Check if already mounted
    if mountpoint -q "${cfg.mountpoint}" 2>/dev/null; then
      echo "Mount point ${cfg.mountpoint} already mounted, skipping"
      exit 0
    fi
    
    # Create mount point if it doesn't exist and execute mount
    sudo mkdir -p "${cfg.mountpoint}"
    sudo mount --bind / "${cfg.mountpoint}/" -o x-mount.mkdir
    
    echo "Bind mount created successfully: ${cfg.mountpoint}"
  '';

in

{
  options.targets.wsl.bindMountRoot = {
    enable = mkEnableOption "WSL cross-instance root filesystem bind mount for non-NixOS systems";
    
    mountpoint = mkOption {
      type = types.str;
      default = "/mnt/wsl/\${WSL_DISTRO_NAME}";
      description = ''
        Mount point for the root filesystem bind mount.
        
        This module is designed for non-NixOS systems only.
        For NixOS systems, use the wsl.crossInstanceMount option from NixOS-WSL.
        
        The mount is configured via /etc/wsl.conf boot command and executed immediately.
        
        References:
        - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings
        - https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#access-the-disk-content
      '';
    };
  };

  config = mkIf cfg.enable {
    warnings = [
      ''
        targets.wsl.bindMountRoot: Configuring WSL cross-instance mount for non-NixOS system
        Mount point: ${cfg.mountpoint}
        Boot command: ${wslConfBootCommand}
        
        Note: You may need to restart your WSL instance for the boot command to take effect.
        For NixOS systems, use wsl.crossInstanceMount from NixOS-WSL instead.
      ''
    ];
    
    home.activation.wslBindMountRoot = lib.hm.dag.entryAfter ["writeBoundary"] ''
      echo "Configuring WSL bind mount for non-NixOS system..."
      echo "Target mount point: ${cfg.mountpoint}"
      
      # Configure wsl.conf
      if [[ -x "${configureWslConf}" ]]; then
        verboseEcho "Running WSL configuration script..."
        "${configureWslConf}"
      else
        echo "Error: WSL configuration script not found or not executable"
        exit 1
      fi
      
      # Execute immediate mount
      if [[ -x "${executeImmediateMount}" ]]; then
        verboseEcho "Executing immediate bind mount..."
        "${executeImmediateMount}"
      else
        echo "Error: Immediate mount script not found or not executable"
        exit 1
      fi
      
      echo "WSL bind mount configuration complete"
      echo "Note: Full functionality requires WSL instance restart"
    '';
  };
}
