{ config, lib, pkgs, wslHostname ? "unknown", ... }:

with lib;

let
  cfg = config.targets.wsl.bindMountRoot;
  
  # Use hostname from specialArgs for mountpoint
  actualMountpoint = if cfg.mountpoint == "/mnt/wsl/\${HOSTNAME}" 
    then "/mnt/wsl/${wslHostname}"
    else cfg.mountpoint;
  
  # Boot command using actual mountpoint
  wslConfBootCommand = "mount --bind / ${actualMountpoint}/ -o x-mount.mkdir";
  
  # Script to configure /etc/wsl.conf
  configureWslConf = pkgs.writeShellScript "configure-wsl-conf" ''
    set -euo pipefail
    
    WSL_CONF="/etc/wsl.conf"
    BACKUP_CONF="$WSL_CONF.backup-$(date +%Y%m%d-%H%M%S)"
    TEMP_CONF=$(mktemp)
    
    echo "Configuring WSL bind mount in $WSL_CONF..."
    
    # Create backup if file exists
    if [[ -f "$WSL_CONF" ]]; then
      sudo cp "$WSL_CONF" "$BACKUP_CONF"
      echo "Backed up existing config to $BACKUP_CONF"
      cp "$WSL_CONF" "$TEMP_CONF"
    else
      cat > "$TEMP_CONF" << 'EOF'
# WSL Configuration
# Generated by home-manager WSL targets module

[boot]
systemd = true

[automount]
enabled = true
EOF
    fi
    
    # Check if [boot] section exists
    if grep -q "^\[boot\]" "$TEMP_CONF"; then
      # Check if our command already exists
      if ! grep -q "mount --bind / ${actualMountpoint}" "$TEMP_CONF"; then
        # Check if existing command exists
        if grep -q "^command" "$TEMP_CONF"; then
          # Preserve existing command by commenting it out
          sed -i "/^\[boot\]/,/^\[/{s|^command|# Previous command|g}" "$TEMP_CONF"
        fi
        # Add our command after [boot] line
        sed -i "/^\[boot\]/a command = \"${wslConfBootCommand}\"" "$TEMP_CONF"
      fi
    else
      # No [boot] section, add it
      cat >> "$TEMP_CONF" << EOF

[boot]
systemd = true
command = "${wslConfBootCommand}"
EOF
    fi
    
    # Apply the configuration atomically
    sudo cp "$TEMP_CONF" "$WSL_CONF"
    rm "$TEMP_CONF"
    
    echo "WSL configuration updated. Boot command: ${wslConfBootCommand}"
  '';
  
  # Script to execute immediate mount
  executeImmediateMount = pkgs.writeShellScript "execute-immediate-mount" ''
    set -euo pipefail
    
    echo "Setting up immediate bind mount: / -> ${actualMountpoint}"
    
    # Check if already mounted
    if mountpoint -q "${actualMountpoint}" 2>/dev/null; then
      echo "Mount point ${actualMountpoint} already mounted, skipping"
      exit 0
    fi
    
    # Create mount point if it doesn't exist and execute mount
    sudo mkdir -p "${actualMountpoint}"
    sudo mount --bind / "${actualMountpoint}/" -o x-mount.mkdir
    
    echo "Bind mount created successfully: ${actualMountpoint}"
  '';

in

{
  options.targets.wsl.bindMountRoot = {
    enable = mkEnableOption "WSL cross-instance root filesystem bind mount for non-NixOS systems";
    
    mountpoint = mkOption {
      type = types.str;
      default = "/mnt/wsl/\${HOSTNAME}";
      description = ''
        Mount point for the root filesystem bind mount.
        
        This module is designed for non-NixOS systems only.
        For NixOS systems, use the wsl.crossInstanceMount option from NixOS-WSL.
        
        The mount is configured via /etc/wsl.conf boot command and executed immediately.
        
        References:
        - https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings
        - https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#access-the-disk-content
      '';
    };
  };

  config = mkIf cfg.enable {
    warnings = [
      ''
        targets.wsl.bindMountRoot: Configuring WSL cross-instance mount for non-NixOS system
        Mount point: ${actualMountpoint}
        Boot command: ${wslConfBootCommand}
        
        Note: You may need to restart your WSL instance for the boot command to take effect.
        For NixOS systems, use wsl.crossInstanceMount from NixOS-WSL instead.
      ''
    ];
    
    home.activation.wslBindMountRoot = lib.hm.dag.entryAfter ["writeBoundary"] ''
      echo "Configuring WSL bind mount for non-NixOS system..."
      echo "Target mount point: ${actualMountpoint}"
      
      # Configure wsl.conf
      if [[ -x "${configureWslConf}" ]]; then
        verboseEcho "Running WSL configuration script..."
        "${configureWslConf}"
      else
        echo "Error: WSL configuration script not found or not executable"
        exit 1
      fi
      
      # Execute immediate mount
      if [[ -x "${executeImmediateMount}" ]]; then
        verboseEcho "Executing immediate bind mount..."
        "${executeImmediateMount}"
      else
        echo "Error: Immediate mount script not found or not executable"
        exit 1
      fi
      
      echo "WSL bind mount configuration complete"
      echo "Note: Full functionality requires WSL instance restart"
    '';
  };
}
